*mlist
*comdeck oxairv
c
c
c  Descriptive sentence goes here.
c
c  Cognizant engineer: ljs.
c
*if def,selap
c
c  variables used in modeling oxidation of zircaloy in presence of air
       common /oxairv/ thbeg(ndax,ndcomp),delwgg(ndax,ndcomp),
     & dheatg(ndax,ndcomp),thbsag(ndax,ndcomp),thsag(ndax,ndcomp),
     & f1air(ndax,ndcomp),ynlimg,yolimg,onemug,
     & fairx1,thxeg(ndax,ndcomp),thkstm(ndax,ndcomp),
     & tmtair(ndax,ndcomp),frcmo2(ndax,ndcomp),frcmar(ndax,ndcomp),
     & frcmn2(ndax,ndcomp),frmh2o(ndax,ndcomp),frairm(ndax,ndcomp),
     & frcmhe(ndax,ndcomp),
     & frcmh2(ndax,ndcomp),froxpl(ndax,ndcomp),rbkarg(ndax,ndcomp),
     & ratwgg(ndax,ndcomp),thbkag(ndax,ndcomp),
     & thbksg(ndax,ndcomp),fperim(ndax,ndcomp),h2prod,h2prd0,pshdwt,
     & iopair,iopeng,nsoxar,
     & nswair(ndax,ndcomp),ibkarg(ndax,ndcomp),nbgair(ndax,ndcomp),
     & ncmths,ntbths,nobrka,
     & mcme108
c  define type for variables involved in oxidation of Zr in presence
c  of air
      real thbeg,delwgg,dheatg,thbsag,thsag,f1air,ynlimg,yolimg,
     & onemug,fairx1,thxeg,ratwgg,thkstm,tmtair,frcmo2,frcmn2,
     & frcmar,frmh2o,frcmhe,frcmh2,frairm,froxpl,rbkarg
       real h2prod,h2prd0,thbkag,thbksg,fperim,pshdwt
      integer nsoxar,nswair,ibkarg,iopair,iopeng,nbgair,                
     & ncmths,ntbths,nobrka,mcme108
c   variables involved in oxidation of zircaloy in air
c   thbeg(k,j) = current effective breakaway thickness of oxide layer
c                at axial node k of component j (m) 
c   delwgg(k,j) = weight gain this time step (kg/m2)
c   dheatg(k,j) = heat generated by oxidation this time step (J)
c   thbsag(k,j) = oxide thickness at time of breakaway of oxide layer
c                 (may be two values, one for pre-oxidation in presence
c                 of steam, other for oxidation in presence of air
c                 (initialized to value of 0.0)
c   thsag(i,icomp) = oxide thickness used in calculating a minimum
c                    thickness (input and output) (m)
c   thkstm(i,icomp) = oxide thickness at end of oxdidation in steam (m)
c                     i = axial node, icomp = component number.
c   f1air(i,icomp) = parameter tracking extent of process leading to
c          breakaway of oxide layer (unitless, initialized to 0.0)
c   ibkarg(i,icomp) = indicator of type of gas present at start of
c            oxidation, initialized to value of zero.
c   rbkarg(i,icomp) = real counterpart to ibkarg(i,icomp)
c                     (defined for plotting)
c   iopair = index specifying correlations for oxidation in steam,
c            air, and oxygen, respectively (user-defined)
c            default value is best to be zero).
c   ynlimg = user-defined minimum value of N2 fraction for
c            breakaway in presence of air (unitess)
c   yolimg = user=defined mimimum value of O2 fraction for
c            oxygen oxidation (unitless)
c   onemug = small length scale (user=defined) (m)
c   iopeng = user-defined variable specifying how much area of
c            cladding involved in oxidation (integer)
c   fairx1 = empirical constant used to tune rate of transition to
c            breakaway of oxide layer, best value is probably 1.
c   thxeg(k,j) = effective thickness of oxide layer (output) (m)
c   ratwgg(k,j) = oxidation rate with respect to weight gain (output)
c   tmtair(k,j) = thickness of metallic layer at start of oxidation
c                 in presence of air (m).
c   frcmo2(k,j) = mole fractions of O2 in fluid, axial node k, comp j.
c   frcmn2(k,j) = mole fractions of N2 in fluid, axial node k, comp j.
c   frcmar(k,j) = mole fractions of Argon in fluid, axial node k, comp j.
c   frmh2o(k,j) = mole fractions H2O in fluid, axial node k, comp j.
c   frcmhe(k,j) = mole fractions of helium in fluid, axial node k, cmp j,
c   frcmh2(k,j) = mole fractions H2 in fluid, axial node k, comp j.
c   frairm(k,j) = mole fractions of air in fluid, axial node k, comp j.
c   froxpl(k,j) = fraction cladding oxidized at axial node k, comp j.
c      h2prod   = total cumulative hydrogen production (kg)
c      h2prd0   = start of time step value of h2prod (kg)
c   thbkag(k,j) = breakaway thickness of oxide for air, node k,cmp j(m)
c   thbksg(k,j) = breakaway thickness of oxide for steam, node k,cmp j(m)
c   fperim(k,j) = fraction of surface area of component j at axial node k
c                 to total surface area of components in the RELAP5 
c                 volume component j resides in.
c                 This variable is not calculated for outer (second)
c                 surface of a shroud component.
c   pshdwt = weighting factor on shroud perimeter in calculation of
c            distribution of flow per component at each axial node,
c            pshdwt = 1. = shroud perimeter weighted same as perimeter
c                          of other components (unitless).
c   nsoxar = index indicating whether modeling to be performed of the
c            oxidation of Zircaloy in presence of air; 0=no, 1=yes.
c   nswair(k,j) = index indicating whether Zicaloy in presence of air
c                 is oxidizing; 0 = no, 1 = yes.
c   nbgair(k,j) = indicator of whether oxidation in presence of air
c                 has started at axial node k, component j;
c                 0 = no; 1 = yes.
c   ncmths = component number whose temperature history is defined by
c            user; 0 = no component has it temperature history defined.
c   ntbths = number of RELAP5 general table defining temperature
c            history of component ncmths.
c   nobrka = index controlling breakup of oxide layer during air oxidation
*endif
