
relap5.exe -i sb.is -U setup -Q
relap5.exe -i sb.i -U 0 -Q
relap5.exe -i sb.i -U 1 -Q
relap5.exe -i sb.i -U 2 -Q
relap5.exe -i sb.i -U 3 -Q
relap5.exe -i sb.i -U 4 -Q
relap5.exe -i sb.i -U 5 -Q
relap5.exe -i sb.i -U 6 -Q
relap5.exe -i sb.i -U 7 -Q
relap5.exe -i sb.i -U 8 -Q
relap5.exe -i sb.i -U 9 -Q
relap5.exe -i sb.i -U 10 -Q
relap5.exe -i sb.i -U 11 -Q
relap5.exe -i sb.i -U 12 -Q
relap5.exe -i sb.i -U 13 -Q
relap5.exe -i sb.i -U 14 -Q
relap5.exe -i sb.i -U 15 -Q
relap5.exe -i sb.i -U 16 -Q
relap5.exe -i sb.i -U 17 -Q
relap5.exe -i sb.i -U 18 -Q
relap5.exe -i sb.i -U 19 -Q
relap5.exe -i sb.i -U 20 -Q
relap5.exe -i sb.i -U 21 -Q
relap5.exe -i sb.i -U 22 -Q
relap5.exe -i sb.i -U 23 -Q
relap5.exe -i sb.i -U 24 -Q
relap5.exe -i sb.i -U 25 -Q
relap5.exe -i sb.i -U 26 -Q
relap5.exe -i sb.i -U 27 -Q
relap5.exe -i sb.i -U 28 -Q
relap5.exe -i sb.i -U 29 -Q
relap5.exe -i sb.i -U 30 -Q
relap5.exe -i sb.i -U 31 -Q
relap5.exe -i sb.i -U 32 -Q
relap5.exe -i sb.i -U 33 -Q
relap5.exe -i sb.i -U 34 -Q
relap5.exe -i sb.i -U 35 -Q
relap5.exe -i sb.i -U 36 -Q
relap5.exe -i sb.i -U 37 -Q
relap5.exe -i sb.i -U 38 -Q
relap5.exe -i sb.i -U 39 -Q
relap5.exe -i sb.i -U 40 -Q
relap5.exe -i sb.i -U 41 -Q
relap5.exe -i sb.i -U 42 -Q
relap5.exe -i sb.i -U 43 -Q
relap5.exe -i sb.i -U 44 -Q
relap5.exe -i sb.i -U 45 -Q
relap5.exe -i sb.i -U 46 -Q
relap5.exe -i sb.i -U 47 -Q
relap5.exe -i sb.i -U 48 -Q
relap5.exe -i sb.i -U 49 -Q
relap5.exe -i sb.i -U 50 -Q
relap5.exe -i sb.i -U 51 -Q
relap5.exe -i sb.i -U 52 -Q
relap5.exe -i sb.i -U 53 -Q
relap5.exe -i sb.i -U 54 -Q
relap5.exe -i sb.i -U 55 -Q
relap5.exe -i sb.i -U 56 -Q
relap5.exe -i sb.i -U 57 -Q
relap5.exe -i sb.i -U 58 -Q
relap5.exe -i sb.i -U 59 -Q
relap5.exe -i sb.ip -U postpr
